name: CI – FastAPI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4
      # Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      # Installer les dépendances dev
      - name: Install dependencies (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip list
      # Linting – qualité du code
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app tests --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
      # Tests unitaires / async
      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov-report=xml --cov-report=term-missing

      # Vérifier la sécurité des dépendances (optionnel)
      - name: Check for security issues
        run: |
          safety check  || true
